export const TEMP_CATEGORY = [
  "Bakery",
  "Personal Hygiene",
  "Fruits",
  "Vegetables",
  "Diary",
  "Provisions",
  "Stationery",
];

export const TEMP_PROD = [
  {
    id: 1,
    brand: "Mordern",
    price: 45,
    prod: "Mordern Bread - Sandwich",
    img: "./bread.jpeg",
  },
  {
    id: 2,
    brand: "Mordern",
    price: 50,
    prod: "Mordern Bread - Whole Wheat",
    img: "./bread.jpeg",
  },
  {
    id: 3,
    brand: "Colgate",
    price: 63,
    prod: "Colgate Toothpaste - 100g",
    img: "./colgate100g.jpeg",
  },
  {
    id: 4,
    brand: "Colgate",
    price: 107,
    prod: "Colgate Toothpaste - 200g",
    img: "./colgate200g.jpeg",
  },
  {
    id: 5,
    brand: "Udhayam",
    price: 75,
    prod: "Toor Dal - 1kg",
    img: "./udhyamtoor.jpeg",
  },
  {
    id: 6,
    brand: "Udhayam",
    price: 90,
    prod: "Urid Dal - 1kg",
    img: "./udhyamurid.jpeg",
  },
  {
    id: 7,
    brand: "Sivaji",
    price: 1435,
    prod: "Rice - 25kg Bag",
    img: "./sivajirice.jpeg",
  },
  {
    id: 8,
    brand: "Classmate",
    price: 35,
    prod: "Classmate Notebook",
    img: "./bread.jpeg",
  },
  {
    id: 9,
    brand: "Reynolds",
    price: 15,
    prod: "Ink Pen",
    img: "./inkpen.jpeg",
  },
  {
    id: 10,
    brand: "Fresho",
    price: 35,
    prod: "Tomato - 1kg",
    img: "./tomato.jpeg",
  },
  {
    id: 11,
    brand: "Fresho",
    price: 60,
    prod: "Beans - 1kg",
    img: "./beans.jpeg",
  },
  {
    id: 12,
    brand: "Fresho",
    price: 20,
    prod: "Potato - 1kg",
    img: "./potato.jpeg",
  },
  {
    id: 13,
    brand: "Fresho",
    price: 48,
    prod: "Cabbage - 1kg",
    img: "./cabbage.jpeg",
  },
  {
    id: 14,
    brand: "Fresho",
    price: 46,
    prod: "Onion - 1kg",
    img: "./onion.jpeg",
  },
  {
    id: 15,
    brand: "Fresho",
    price: 54,
    prod: "Carrot - 1kg",
    img: "./carrot.jpeg",
  },
];
